const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const packs = [
['01','Aurora Command','SaaS / AI dashboard','Parallax glow'],['02','Studio Signal','Agency / portfolio','Text reveal + pointer line'],['03','Neon Gateway','Tech launch','Cursor glow + grid pulse'],['04','Commerce Lift','Ecommerce landing','Card tilt + metrics'],['05','Editorial Prestige','Blog / luxury content','Scroll fade + progress'],['06','Soft SaaS Onboarding','Onboarding / app','Feature pill rotation'],['07','Finance Trust','B2B finance','KPI count-up'],['08','Creative Motion','Campaign / studio','Gradient shift + shape float'],['09','Developer Console','API / docs','Terminal typing'],['10','Luxury Edge','High-end brand','Geometric hover reveal']
].map(([id,name,useCase,interaction])=>({id,name,useCase,interaction}));
const selector = document.getElementById('packSelector'), meta = document.getElementById('activeMeta'), host = document.getElementById('activeHeroHost');
const htmlEl = document.getElementById('snippetHtml'), cssEl = document.getElementById('snippetCss'), jsEl = document.getElementById('snippetJs');
const gallery = document.getElementById('heroGallery'); const feedback = document.getElementById('copyFeedback');
const heroHtml = id => `<section class="h${id}_hero"><div class="h${id}_hero__inner"><div class="h${id}_hero__content"><p class="h${id}_hero__eyebrow">Pack ${id}</p><h3 class="h${id}_hero__title">${packs.find(p=>p.id===id).name}</h3><p class="h${id}_hero__lead">Built for ${packs.find(p=>p.id===id).useCase}.</p><div class="h${id}_hero__actions"><a href="#" class="hero-cta">Get started</a></div></div><div class="h${id}_hero__visual"><div class="h${id}_hero__card">Preview card</div></div></div></section>`;
const heroCss = id => `/* Hero Pack ${id} */\n.h${id}_hero { /* dedicated styles */ }`;
const heroJs = id => `// Hero Pack ${id} init\ninitHero${id}();`;
function renderSelector(){packs.forEach((p,i)=>{const b=document.createElement('button');b.className='dv_pack_btn';b.role='tab';b.dataset.id=p.id;b.setAttribute('aria-selected',i===0?'true':'false');b.innerHTML=`<strong>${p.id} — ${p.name}</strong><br><small>${p.useCase}</small><br><small>${p.interaction}</small>`;b.addEventListener('click',()=>activate(p.id));selector.appendChild(b);});}
function renderGallery(){packs.forEach(p=>{const a=document.createElement('article');a.className='hero-card';a.innerHTML=`<h3>${p.id} — ${p.name}</h3>${heroHtml(p.id)}`;gallery.appendChild(a);});}
function activate(id){selector.querySelectorAll('button').forEach(b=>b.setAttribute('aria-selected',b.dataset.id===id));const p=packs.find(x=>x.id===id);meta.innerHTML=`<p><strong>${p.id} — ${p.name}</strong></p><p>Use case: ${p.useCase}</p><p>Interaction: ${p.interaction}</p><p>Implementation notes: copy only h${id}_ HTML/CSS/JS sections.</p>`;host.innerHTML=heroHtml(id);htmlEl.textContent=heroHtml(id);cssEl.textContent=heroCss(id);jsEl.textContent=heroJs(id);initHero(id);} 
function initHero(id){if(reduceMotion) return; const root=host.firstElementChild;if(!root) return;
if(id==='01'||id==='08'){root.onpointermove=e=>{const r=root.getBoundingClientRect();root.style.setProperty(id==='01'?'--x':'--mx',((e.clientX-r.left)/r.width*100)+'%');root.style.setProperty(id==='01'?'--y':'--my',((e.clientY-r.top)/r.height*100)+'%');};}
if(id==='02') requestAnimationFrame(()=>root.classList.add('is-ready'));
if(id==='03'){const orb=document.createElement('i');orb.className='h03_hero__orb';root.appendChild(orb);root.onpointermove=e=>{const r=root.getBoundingClientRect();root.style.setProperty('--ox',((e.clientX-r.left)/r.width*100)+'%');root.style.setProperty('--oy',((e.clientY-r.top)/r.height*100)+'%');};}
if(id==='04'){const card=root.querySelector('.h04_hero__product')||root.querySelector('.h04_hero__card');root.onpointermove=e=>{if(!card)return;const r=root.getBoundingClientRect();card.style.setProperty('--rx',(((e.clientY-r.top)/r.height-.5)*-8)+'deg');card.style.setProperty('--ry',(((e.clientX-r.left)/r.width-.5)*8)+'deg');};}
if(id==='05'){window.addEventListener('scroll',()=>{const p=Math.min(100,Math.max(0,(window.scrollY/300)*100));root.style.setProperty('--p',p+'%');},{passive:true});}
if(id==='06'){let i=0;const pills=[...root.querySelectorAll('.h06_hero__pill')];setInterval(()=>{pills.forEach(x=>x.classList.remove('is-on'));if(pills.length)pills[(i++)%pills.length].classList.add('is-on');},1400);}
if(id==='07'){root.querySelectorAll('.h07_hero__kpi').forEach(el=>{const end=Number(el.dataset.kpi||120);let v=0;const t=setInterval(()=>{v+=Math.ceil(end/20);el.textContent=Math.min(v,end);if(v>=end)clearInterval(t);},60);});}
if(id==='09'){const term=root.querySelector('.h09_hero__term');if(term){const txt='> npm run launch\n✔ services online\n✔ latency stable';let i=0;const t=setInterval(()=>{term.textContent=txt.slice(0,i++);if(i>txt.length)clearInterval(t);},22);}}
if(id==='10'){root.onpointermove=e=>{const g=root.querySelector('.h10_hero__geo');if(g)g.style.setProperty('--rot',(((e.offsetX/root.clientWidth)-.5)*30)+'deg');};}}
document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const type=btn.dataset.copy;const text=type==='html'?htmlEl.textContent:type==='css'?cssEl.textContent:jsEl.textContent;await navigator.clipboard.writeText(text);feedback.textContent=`${type.toUpperCase()} copied.`;}));
renderSelector();renderGallery();activate('01');
